config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'games#recent'
  resources :games, :plays, :players

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :plays
  belongs_to :winner, class_name: "Player", foreign_key: "winner_id"
end

app/models/play.rb
class Play < ApplicationRecord
  belongs_to :game
  belongs_to :player  
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :plays
  has_many :games, through: :Plays
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  self.primary_key = :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:fname, :lname, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:fname, :lname, :email, :password, :current_password)}
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def recent
    @recent_games = Game.all().order(id: :desc).limit(3)
  end

  def new
    @game = Game.new
    @players = Player.all().order(name: :asc)
  end

  def create

  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end

  def show
    @player = Player.find(params[:id])
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)

    if @player.save
      redirect_to @player
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def player_params
      params.require(:player).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/new.html.erb
<h2>Create a New Game</h2>

<h3>Select players...</h3>

<%= form_with model: @game do |f| %>

<% @players.each do |p| %>
  <%= f.check_box :player_id %><%= p.name %></br>
<% end %>
<%= f.submit "Create" %>
<% end %>

app/views/games/recent.html.erb
<h2>Recent Games...</h2>

<table class="table">
  <tr><th>Date</th><th>Winner</th></tr>
  <%  @recent_games.each do |g| %>
  <tr><td><%= g.date %></td><td><%= g.winner.name %></td></tr>
  <% end %>
</table>

<h2><%= link_to "Score a New Game", new_game_path %></h2>

<%= link_to "Edit Players", players_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wingspanscore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1><%= link_to "Wingspan Scoring", root_path %></h1>
    <p class="navbar-text float-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>

    <p>
    </p>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/players/index.html.erb
<h1>List of Players</h1>
<ul>
<% @players.each do |p| %>
  <li><%= p.name %></li>
<% end %>
<%= link_to "Create a New Player", new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= form_with model: @player do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>